name: PHP Code Sniffer

on: 
  push:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer dependecies
        run: composer install
            vendor/bin/grumphp.php